---

- name: Install requirements (RedHat)
  yum:
    name:
      - postfix
      - ca-certificates
      - mailx

- name: Install DKIM requirements (RedHat)
  yum:
    name: opendkim
  when: postfix_dkim
