---

- name: Install requirements (Debian)
  apt:
    name:
      - postfix
      - ca-certificates
      - mailutils
      - spamassassin
      - spamc

- name: Install SPF (Debian)
  apt:
    name: postfix-policyd-spf-python
  when: postfix_spf

- name: Install sasl requirements (Debian)
  apt:
    name:
      - libsasl2-2
      - sasl2-bin
      - libsasl2-modules
  when: postfix_smtpd_auth_sasl_enable is defined

- name: Install DKIM requirements (Debian)
  apt:
    name:
      - opendkim
      - opendkim-tools
  when: postfix_dkim

- name: Install DMARC requirements (Debian)
  apt:
    name: opendmarc
  when: postfix_dmarc

- name: Install PCRE [Perl Compatible Reg. Exp.] (Debian)
  apt:
    name: postfix-pcre
  when: postfix_rewrite_sender_address
